Repository skfl/andersen-task, pull requests merged in 2023-04, with the labels that each got.

#21 Feature: "User"
  pom.xml
  src/main/java/com/andersentask/bookshop/user/repository/UserCollectionRepositoryImpl.java
  src/main/java/com/andersentask/bookshop/user/repository/UserRepository.java
  src/main/java/com/andersentask/bookshop/user/repository/interfaces/UserCollectionRepository.java
  src/main/java/com/andersentask/bookshop/user/service/UserService.java
  src/test/java/com/andersentask/bookshop/user/repository/UserRepositoryTest.java
  src/test/java/com/andersentask/bookshop/user/service/UserServiceTest.java
Labels: enhancement

#20 Feature: "Request entity repository service"
  src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
  src/main/java/com/andersentask/bookshop/request/entities/Request.java
  src/main/java/com/andersentask/bookshop/request/entities/enums/RequestStatus.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
Labels: enhancement

#28 Feature: "Add logback"
  pom.xml
  src/main/resources/logback.xml
Labels: enhancement

#29 Fix: "Order and request"
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/enums/OrderStatus.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
Labels: fix

#22 Fix: "Order"
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/enums/OrderStatus.java
  src/main/java/com/andersentask/bookshop/order/facade/OrderFacade.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
Labels: bug, duplicate, Vlad, fix

#32 Fix: "Remove unnecessary method from BookStatus"
  src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/book/repositories/interfaces/BookCollectionRepository.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
Labels: fix

#31 Fix: "order and request"
  src/main/java/com/andersentask/bookshop/order/enums/OrderStatus.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
Labels: fix

#48 Feature: "Add console interface and fix request/order logic"
  src/main/java/com/andersentask/bookshop/BookshopApplication.java
  src/main/java/com/andersentask/bookshop/book/enums/BookSort.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
  src/main/java/com/andersentask/bookshop/console/DefaultMessages.java
  src/main/java/com/andersentask/bookshop/console/EntityFactory.java
  src/main/java/com/andersentask/bookshop/console/UserCommunication.java
  src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
  src/main/java/com/andersentask/bookshop/order/enums/OrderSort.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/entities/Request.java
  src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
Labels: enhancement, help wanted, invalid, Vlad

#51 Fix: "Change AbstractCollectionRepository interface name"
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/common/CollectionRepository.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/user/repository/UserRepository.java
Labels: fix

#52 Feature: "Serialization/deserialization application state"
  pom.xml
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
  src/main/java/com/andersentask/bookshop/console/UserCommunication.java
  src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
  src/main/java/com/andersentask/bookshop/utils/serialization/RepositoryDeserializer.java
  src/main/java/com/andersentask/bookshop/utils/serialization/RepositorySerializer.java
Labels: enhancement

#53 Feature: "Custom property"
  console.properties
  src/main/java/com/andersentask/bookshop/console/UserCommunication.java
Labels: enhancement

#55 Fix: "Book enum"
  src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
Labels: fix

#56 Fix: "General Style"
  src/main/java/com/andersentask/bookshop/book/entities/Book.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/common/CollectionRepository.java
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
  src/main/java/com/andersentask/bookshop/console/EntityFactory.java
  src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/entities/Request.java
  src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
  src/main/java/com/andersentask/bookshop/user/enums/Role.java
  src/main/java/com/andersentask/bookshop/user/service/UserService.java
  src/main/java/com/andersentask/bookshop/utils/serialization/RepositoryDeserializer.java
Labels: fix

#54 Fix: "Order and Book from Double to BigDecimal"
  src/main/java/com/andersentask/bookshop/book/entities/Book.java
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/console/EntityFactory.java
  src/main/java/com/andersentask/bookshop/console/UserCommunication.java
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
Labels: fix

#58 Fix: "Book status repository"
  src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/common/CollectionRepository.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/user/repository/UserRepository.java
  src/test/java/com/andersentask/bookshop/user/repository/UserRepositoryTest.java
Labels: fix

#59 Fix: "Commands and UserCommunication"
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/console/DefaultMessages.java
  src/main/java/com/andersentask/bookshop/console/UserCommunication.java
Labels: Vlad, fix

#60 Update: "Remove unnecessary dependency"
  pom.xml
Labels: enhancement

#61 Test: "Services and repositories"
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/test/java/com/andersentask/bookshop/book/repositories/BookRepositoryTest.java
  src/test/java/com/andersentask/bookshop/book/services/BookServiceTest.java
  src/test/java/com/andersentask/bookshop/order/repositories/OrderRepositoryTest.java
  src/test/java/com/andersentask/bookshop/order/service/OrderServiceTest.java
  src/test/java/com/andersentask/bookshop/request/repository/RequestRepositoryTest.java
  src/test/java/com/andersentask/bookshop/request/services/RequestServiceTest.java
  src/test/java/com/andersentask/bookshop/user/service/UserServiceTest.java
Labels: test

#62 Refactor: "Pre-release refactor"
  src/main/java/com/andersentask/bookshop/BookshopApplication.java
  src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/console/EntityFactory.java
  src/main/java/com/andersentask/bookshop/console/UserCommunication.java
  src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/enums/OrderStatus.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/entities/Request.java
  src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
  src/main/java/com/andersentask/bookshop/user/entities/User.java
  src/main/java/com/andersentask/bookshop/utils/serialization/RepositoryDeserializer.java
Labels: enhancement, refactor

#64 Fix: "Services and repositories"
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
  src/test/java/com/andersentask/bookshop/order/service/OrderServiceTest.java
  src/test/java/com/andersentask/bookshop/request/services/RequestServiceTest.java
Labels: enhancement, fix

#66 Feature: "Servlet version"
  pom.xml
  src/main/java/com/andersentask/bookshop/BookshopApplication.java
  src/main/java/com/andersentask/bookshop/http/HttpInterface.java
  src/main/java/com/andersentask/bookshop/http/README.md
  src/main/java/com/andersentask/bookshop/http/servlets/ChangeBookStatusServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/ChangeOrderStatusServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/CreateOrderServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/CreateRequestServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/ExitServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetAllBooksFromOrderServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetBookServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetBooksAndNumberOfRequestsServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetNumberOfRequestsOnBookServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetOrderServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetRequestsServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/JsonServlet.java
Labels: enhancement

#68 Feature: "Request to db jdbc"
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestMapper.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestSQLCommands.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
  src/main/resources/db/changelog/changeset/create-requests-table.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/test/java/com/andersentask/bookshop/request/repository/RequestRepositoryTest.java
  src/test/java/com/andersentask/bookshop/request/services/RequestServiceTest.java
Labels: enhancement, good first issue, invalid, Vlad

#69 Feature: "Add JDBC Repository implementations"
  pom.xml
  src/main/java/com/andersentask/bookshop/book/repositories/BookMapper.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookSQLCommands.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/console/Commands.java
  src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
  src/main/java/com/andersentask/bookshop/http/servlets/JsonServlet.java
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderBooksSQLCommands.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderMapper.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderSQLCommands.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestMapper.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestSQLCommands.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
  src/main/java/com/andersentask/bookshop/utils/serialization/RepositoryDeserializer.java
  src/main/java/com/andersentask/bookshop/utils/serialization/RepositorySerializer.java
  src/main/resources/db/changelog/changeset/create-books-table.yaml
  src/main/resources/db/changelog/changeset/create-initial-books-data.yaml
  src/main/resources/db/changelog/changeset/create-order-books-table.yaml
  src/main/resources/db/changelog/changeset/create-orders-table.yaml
  src/main/resources/db/changelog/changeset/create-requests-table.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/test/java/com/andersentask/bookshop/book/repositories/BookRepositoryTest.java
  src/test/java/com/andersentask/bookshop/book/services/BookServiceTest.java
  src/test/java/com/andersentask/bookshop/request/repository/RequestRepositoryTest.java
  src/test/java/com/andersentask/bookshop/request/services/RequestServiceTest.java
Labels: enhancement

#77 Feature: "Move to spring boot"
  pom.xml
  src/main/java/com/andersentask/bookshop/AppContextConfig.java
  src/main/java/com/andersentask/bookshop/BookshopApplication.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookJPQLQueries.java
  src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
  src/main/java/com/andersentask/bookshop/book/services/BookService.java
  src/main/java/com/andersentask/bookshop/broker/Commands.java
  src/main/java/com/andersentask/bookshop/broker/EntityFactory.java
  src/main/java/com/andersentask/bookshop/controllers/BookController.java
  src/main/java/com/andersentask/bookshop/controllers/OrderController.java
  src/main/java/com/andersentask/bookshop/controllers/README.md
  src/main/java/com/andersentask/bookshop/controllers/RequestController.java
  src/main/java/com/andersentask/bookshop/exception/GlobalExceptionHandler.java
  src/main/java/com/andersentask/bookshop/http/HttpInterface.java
  src/main/java/com/andersentask/bookshop/http/README.md
  src/main/java/com/andersentask/bookshop/http/servlets/ChangeBookStatusServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/ChangeOrderStatusServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/CreateOrderServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/CreateRequestServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetAllBooksFromOrderServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetBookServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetBooksAndNumberOfRequestsServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetNumberOfRequestsOnBookServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetOrderServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/GetRequestsServlet.java
  src/main/java/com/andersentask/bookshop/http/servlets/JsonServlet.java
  src/main/java/com/andersentask/bookshop/order/entities/Order.java
  src/main/java/com/andersentask/bookshop/order/enums/OrderSort.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderJPQLQueries.java
  src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
  src/main/java/com/andersentask/bookshop/order/service/OrderService.java
  src/main/java/com/andersentask/bookshop/request/entities/Request.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestJPQLQueries.java
  src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
  src/main/java/com/andersentask/bookshop/request/services/RequestService.java
  src/main/java/com/andersentask/bookshop/response/ApplicationError.java
  src/main/resources/application.properties
Labels: enhancement, Vlad
